# Generated by Django 5.0.4 on 2024-06-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='client',
            field=models.CharField(max_length=200),
        ),
    ]
