# Generated by Django 5.0.4 on 2024-09-18 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0002_alter_sale_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('logo', models.ImageField(upload_to='logos/', verbose_name='Логотип')),
                ('website', models.URLField(max_length=255, verbose_name='Сайт компании')),
            ],
        ),
    ]
