# Generated by Django 5.0.4 on 2024-10-13 05:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0003_partnercompany'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinfo',
            name='description',
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='address',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='certificate',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='logos/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='history',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='logo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='logos/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='phone',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='video',
            field=models.FileField(default=django.utils.timezone.now, upload_to='videos/'),
            preserve_default=False,
        ),
    ]
